services:
  revelation-frontend:
    image: ghcr.io/${REPOSITORY_OWNER:-deeyosoft-solutions}/revelation-frontend:${IMAGE_TAG_FRONTEND:-prod}
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      NEXT_PUBLIC_API_URL: https://api.revelationpestcontrol.com/api/v1
    restart: unless-stopped
    networks:
      - revelation-network

networks:
  revelation-network:
    driver: bridge
